name: 'Deploy APK in Firebase App Distribution'
description: "Deploy APK in Firebase App Distribution"
inputs:
  buildType:
    description: "Build type"
    required: true
  googleApplicationCredentials:
    description: 'Google Application Credentials'
    required: true
outputs: { }
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: assembled-builds
        path: app/build/outputs/apk/

    - uses: actions/download-artifact@v3
      with:
        name: google-services
        path: app/build/generated/res/google-services/

    - name: Decode service credentials
      id: decode_service_credentials
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: "service_credentials.json"
        fileDir: "./config"
        encodedString: ${{ inputs.googleApplicationCredentials }}

    - name: Deploy APK in Firebase App Distribution
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true
        arguments: appDistributionUpload${{ inputs.buildType }} --stacktrace --scan --info
#        arguments: appDistributionUpload${{ inputs.buildType }} --releaseNotes="${{ inputs.releaseNotes }}" --stacktrace --scan
