object Modules {
  const val app = ":app"
  const val base = ":base"
  const val baseTest = ":base-test"
  const val baseAndroidTest = ":base-android-test"
  const val navigator = ":navigator"

  const val featureNetwork = ":features:network"

  const val featureBase = ":features:base"
  const val featureAccount = ":features:account"
  const val featureMovie = ":features:movie"
  const val featureHome = ":features:home"
  const val featureMovieList = ":features:list"
  const val featureLogin = ":features:login"
  const val featureTMDBConnect = ":features:tmdb"
  const val featureError = ":features:error"

  const val libraryAndroid = ":libraries:android"
  const val libraryAndroidTest = ":libraries:android-test"
  const val libraryBase = ":libraries:base"
  const val libraryCoroutines = ":libraries:coroutines"
  const val libraryCoroutinesTest = ":libraries:coroutines-test"
  const val libraryGlide = ":libraries:glide"
  const val libraryOkHttp3 = ":libraries:okhttp3"
  const val libraryPagination = ":libraries:pagination"
  const val libraryPaginationCo = ":libraries:pagination-co"
  const val libraryPermissions = ":libraries:permissions"
  const val libraryPreferences = ":libraries:preferences"
  const val libraryRetrofit = ":libraries:retrofit"
  const val libraryRetrofitCo = ":libraries:retrofit-co"
  const val libraryThreeten = ":libraries:threeten"
}
