# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ releases/^[0-9]+\.[0-9]+$/ ]
  pull_request:
    branches: [ releases/^[0-9]+\.[0-9]+$/ ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "test"
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew -Pci --console=plain testDebugUnitTest jacocoTestReportDebug --stacktrace

      - name: Upload to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v1

