# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Workflow events: Controls when the action will run.
# More info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Triggers the workflow on pull request events but only for the master branch
  create:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Enable debug for the `gradle-build-action` cache operations
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  checkstyle:
    if: startsWith(github.ref, 'refs/heads/release/')
    name: Check code (detekt)
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup machine
        uses: ./.github/actions/common_setup

      - name: Load secrets
        uses: ./.github/actions/load_secrets
        with:
          tmdb-token-v3: ${{ secrets.TMDB_TOKEN_V3 }}
          tmdb-token-v4: ${{ secrets.TMDB_TOKEN_V4 }}

      - name: Check code via Detekt
        uses: gradle/gradle-build-action@v3
        with:
          arguments: detekt --stacktrace --scan

  assemble:
    needs: [ checkstyle ]
    if: success() && startsWith(github.ref, 'refs/heads/release/')
    name: Assemble apk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: [ "Debug", "Release" ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup machine
        uses: ./.github/actions/common_setup

      - name: Load secrets
        uses: ./.github/actions/load_secrets
        with:
          tmdb-token-v3: ${{ secrets.TMDB_TOKEN_V3 }}
          tmdb-token-v4: ${{ secrets.TMDB_TOKEN_V4 }}

      - name: Assemble APK ${{ matrix.buildType }}
        uses: ./.github/actions/assemble_apk
        with:
          buildType: ${{ matrix.buildType }}
          signingFiles: ${{ secrets.RELEASE_FILES }}

  test:
    needs: [ checkstyle ]
    if: success() && startsWith(github.ref, 'refs/heads/release/')
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup machine
        uses: ./.github/actions/common_setup

      - name: Load secrets
        uses: ./.github/actions/load_secrets
        with:
          tmdb-token-v3: ${{ secrets.TMDB_TOKEN_V3 }}
          tmdb-token-v4: ${{ secrets.TMDB_TOKEN_V4 }}

      - name: Unit tests
        uses: ./.github/actions/unit_tests

  instrumental-test:
    needs: [ checkstyle ]
    if: success() && startsWith(github.ref, 'refs/heads/release/')
    name: Run Android Instrumental Tests
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 45
    strategy:
      matrix:
        arch: [ x86_64 ]
        target: [ google_apis ]
        channel: [ stable ]
        api-level: [ 29 ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup machine
        uses: ./.github/actions/common_setup

      - name: Load secrets
        uses: ./.github/actions/load_secrets
        with:
          tmdb-token-v3: ${{ secrets.TMDB_TOKEN_V3 }}
          tmdb-token-v4: ${{ secrets.TMDB_TOKEN_V4 }}

      - name: Launch Instrumental tests
        uses: ./.github/actions/instrumental_tests
        with:
          arch: ${{ matrix.arch }}
          target: ${{ matrix.target }}
          channel: ${{ matrix.channel }}
          api-level: ${{ matrix.api-level }}

  reports:
    needs: [ test, instrumental-test ]
    if: success() && startsWith(github.ref, 'refs/heads/release/')
    name: Generate reports
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup machine
        uses: ./.github/actions/common_setup

      - name: Load secrets
        uses: ./.github/actions/load_secrets
        with:
          tmdb-token-v3: ${{ secrets.TMDB_TOKEN_V3 }}
          tmdb-token-v4: ${{ secrets.TMDB_TOKEN_V4 }}

      - name: Generate jacoco reports and upload to codecov
        uses: ./.github/actions/generate_reports
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy-firebase:
    needs: [ test, instrumental-test ]
    if: success() && startsWith(github.ref, 'refs/heads/release/')
    name: Build & Upload to Firebase App Distribution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildType: [ "Debug", "Release" ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup machine
        uses: ./.github/actions/common_setup

      - name: Deploy APK in Firebase App Distribution
        uses: ./.github/actions/deploy_in_firebase
        with:
          buildType: ${{ matrix.buildType }}
          googleApplicationCredentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

#  deploy-playstore:
#    name: Build & Upload to Playstore
#    if: startsWith(github.ref, 'refs/tags/')
#    runs-on: ubuntu-latest
#
#    needs: test
#
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#          cache: 'gradle'
#
#      - name: Publish
#        env:
#          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
#        run: bash ./gradlew publishBundle --stacktrace

  status:
#    needs: [ test, instrumental-test, reports, deploy-firebase, deploy-playstore ]
    needs: [ assemble, test, instrumental-test, reports, deploy-firebase ]
    if: success()
    name: Status
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
